### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#1077]
The change introduced in https://github.com/deis/controller/pull/1061 has started to cause unit test failures:

```
...................E....................................................................................................................................................................................................................................................................

======================================================================

ERROR: test_gather_app_settings (api.tests.test_app.AppTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.0/src/request-mock/requests_mock/mocker.py", line 180, in inner

    return func(*args, **kwargs)

  File "/opt/python/3.5.0/lib/python3.5/unittest/mock.py", line 1157, in patched

    return func(*args, **keywargs)

  File "/home/travis/build/deis/controller/rootfs/api/tests/test_app.py", line 589, in test_gather_app_settings

    3)

  File "/home/travis/build/deis/controller/rootfs/api/models/app.py", line 994, in _gather_app_settings

    envs = self._build_env_vars(release)

  File "/home/travis/build/deis/controller/rootfs/api/models/app.py", line 797, in _build_env_vars

    if release.build.type == 'buildpack':

AttributeError: 'NoneType' object has no attribute 'type'
```
