### PR TITLE
fix(api): check latest release, not app

### LINKED ISSUE #668: controller restoring application
Seeing this when testing workflow-beta3:

```
><> kd logs -p deis-controller-ecri7
system information:
Django Version: 1.9.5
Python 3.5.1
Django checks:
System check identified no issues (2 silenced).
Health Checks:
Checking if database is alive
Database is alive!
Database Migrations:
Operations to perform:
  Apply all migrations: guardian, auth, sessions, authtoken, api, contenttypes
Running migrations:
  No migrations to apply.
[2016-04-26 20:25:46 +0000] [32] [INFO] Starting gunicorn 19.4.5
[2016-04-26 20:25:46 +0000] [32] [INFO] Listening at: http://0.0.0.0:8000 (32)
[2016-04-26 20:25:46 +0000] [32] [INFO] Using worker: sync
[2016-04-26 20:25:46 +0000] [36] [INFO] Booting worker with pid: 36
[2016-04-26 20:25:46 +0000] [37] [INFO] Booting worker with pid: 37
[2016-04-26 20:25:46 +0000] [46] [INFO] Booting worker with pid: 46
[2016-04-26 20:25:46 +0000] [51] [INFO] Booting worker with pid: 51
[2016-04-26 20:25:46 +0000] [56] [INFO] Booting worker with pid: 56
DEBUG create test-592511760
DEBUG create test-582634844
DEBUG create test-530181643
DEBUG create test-516031150
DEBUG create test-583659479
DEBUG create test-358426383
DEBUG create test-646605029
DEBUG create test-326446264
DEBUG create test-613572783
DEBUG create test-652927453
INFO test-652927453: config test-652927453-5043cfb updated
INFO test-358426383: config test-358426383-af33ac6 updated
INFO test-583659479: config test-583659479-f94f80d updated
INFO test-613572783: config test-613572783-9b8c83c updated
INFO test-326446264: config test-326446264-435a53a updated
INFO test-646605029: config test-646605029-1091660 updated
INFO test-358426383: config test-358426383-aa1d4c2 updated
INFO test-646605029: config test-646605029-fefd015 updated
INFO test-583659479: config test-583659479-3c78531 updated
INFO test-516031150: config test-516031150-42039e1 updated
INFO test-530181643: config test-530181643-1a3353b updated
INFO test-592511760: config test-592511760-b077b46 updated
INFO test-582634844: config test-582634844-febc70f updated
Publishing DB state to kubernetes...
Deploying available applications
Traceback (most recent call last):
  File "/app/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/api/management/commands/load_db_state_to_k8s.py", line 27, in handle
    if application.build is None:
AttributeError: 'App' object has no attribute 'build'
```

### PR DESCRIPTION
**Pull request by bacongobbler**
An application does not have a build attribute, but its latest release does.

closes #668

### CODE REVIEW

**Comment by bacongobbler** [comment]
this was broken with https://github.com/deis/controller/commit/ffc65ee2a172196f8332f9a0345fe670f8841776
